runtime: nodejs10

# Хэндлеры прописал, потому что Гугл выдавал ошибку при деплое
# https://stackoverflow.com/questions/50842007/no-urlmap-entries-found-in-application-configuration/50842459
handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

env_variables:
  NODE_ENV: "production"
  GITLAB_API: ${GITLAB_API}
  GITLAB_TOKEN: ${GITLAB_TOKEN}